export default {
  "0058b4c6": [() => import(/* webpackChunkName: "0058b4c6" */ "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json"), "@generated/docusaurus-plugin-content-docs/default/p/docs-175.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/docs-175.json")],
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1df93b7f": [() => import(/* webpackChunkName: "1df93b7f" */ "@site/src/pages/index.tsx"), "@site/src/pages/index.tsx", require.resolveWeak("@site/src/pages/index.tsx")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "23c8262c": [() => import(/* webpackChunkName: "23c8262c" */ "@site/docs/architecture/core.md"), "@site/docs/architecture/core.md", require.resolveWeak("@site/docs/architecture/core.md")],
  "4a042698": [() => import(/* webpackChunkName: "4a042698" */ "@site/docs/api/openapi.md"), "@site/docs/api/openapi.md", require.resolveWeak("@site/docs/api/openapi.md")],
  "4c678320": [() => import(/* webpackChunkName: "4c678320" */ "@site/src/pages/markdown-page.mdx"), "@site/src/pages/markdown-page.mdx", require.resolveWeak("@site/src/pages/markdown-page.mdx")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "6a910985": [() => import(/* webpackChunkName: "6a910985" */ "@site/docs/concepts/theory.md"), "@site/docs/concepts/theory.md", require.resolveWeak("@site/docs/concepts/theory.md")],
  "9ab60744": [() => import(/* webpackChunkName: "9ab60744" */ "@site/docs/architecture/authentication.md"), "@site/docs/architecture/authentication.md", require.resolveWeak("@site/docs/architecture/authentication.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aa63a0b5": [() => import(/* webpackChunkName: "aa63a0b5" */ "@site/docs/architecture/infrastructure.md"), "@site/docs/architecture/infrastructure.md", require.resolveWeak("@site/docs/architecture/infrastructure.md")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],};
