apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aroradb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/BhawukHQ/Bhawuk-AroraDB.git'
    targetRevision: HEAD
    path: helm/aroradb
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: aroradb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
